sudo: false
language: ruby

rvm:
 - "2.0.0"
 - "2.1.0"
 - "2.2.0"
 - rbx

before_install: gem install bundler -v 1.15.4
script:
   - bundle exec rubocop --version
   - bundle exec rubocop -D .
   - bundle exec rspec
