sudo: false
language: ruby

# rvm:
#  - "2.0.0"
#  - "2.1.0"
#  - "2.2.0"
#  - rbx
#  - "2.5.0"

#before_install: gem install bundler -v 1.15.4
script:
   - bundle install
   - bundle exec rubocop --version
   - bundle exec rubocop -D .
   - bundle exec rspec
   - cd SampleProjects/TestSomething
   - bundle install
   - bundle exec arduino_ci_remote.rb
